name: Zoe Mallett
favicon: null
layout_spectrum: 0.8588175175245851
typography_spectrum: 0.36695349123328924
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.2250477960333228
  lightness: 0.5112308112438768
  saturation: 0.5472596348263323
  rhythmicContrast: 0.17479580081999302
purpose: []
